name: fatiando-dev
dependencies:
    - python=2.7
    - pip
    - numpy
    - scipy
    - matplotlib
    - numba
    - future
    - basemap
    - pillow
    - jupyter
    - mayavi
    - sphinx
    - pytest
    - pytest-cov
    - coverage
    - pep8=1.6.2
    - cython
    - pip:
        # Need the dev version of sphinx-gallery for the Mayavi plot thumbnails
        - https://github.com/sphinx-gallery/sphinx-gallery/archive/master.zip
        - sphinx_bootstrap_theme==0.4.5
